version: '3'
services:
    server:
        build: .
        command: npm start
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - PORT=8000
